### ISSUE TITLE
showFields in Arrays no longer works

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe-schemas#19]
At least since 6891fa7919c92e0c4, showFields within an array item no longer works. Rolling back to 6891fa7919c92e0c4 does make it work.

**Comment by boutell** [comment]
Paging Dr. @jth- !

**Comment by jsumnersmith** [comment]
He and I looked at it earlier. I'll try to debug this further next week.

> On Feb 17 2016, at 1:03 pm, Tom Boutell &lt;notifications@github.com&gt;
wrote:  

>

> Paging Dr. [@jth-](https://github.com/jth-) !

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/punkave
/apostrophe-schemas/issues/19#issuecomment-185327553).![](https://github.com/n
otifications/beacon/ABkGkWj69_psuwVhiT2h8cv9TAls6a2Nks5plK1lgaJpZM4HcV_u.gif)
